// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwHK_OYPoRAAaPCy9rShOsssoLOnfdAiY',
    appId: '1:174515227682:web:51fa3a35eb3407210fce7b',
    messagingSenderId: '174515227682',
    projectId: 'tm-book',
    authDomain: 'tm-book.firebaseapp.com',
    storageBucket: 'tm-book.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH5JRyYMbInjlYo1Yl8oc9EIqRNQnalh0',
    appId: '1:174515227682:android:a3a7c878c39b66a80fce7b',
    messagingSenderId: '174515227682',
    projectId: 'tm-book',
    storageBucket: 'tm-book.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp-Cp0YrveNkY4-uU2diGkOjWwy-VLq-M',
    appId: '1:174515227682:ios:15d3add31059ba240fce7b',
    messagingSenderId: '174515227682',
    projectId: 'tm-book',
    storageBucket: 'tm-book.appspot.com',
    iosClientId: '174515227682-9lioso6m0psjavgnkf6q4802q943ae16.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookTiming',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp-Cp0YrveNkY4-uU2diGkOjWwy-VLq-M',
    appId: '1:174515227682:ios:15d3add31059ba240fce7b',
    messagingSenderId: '174515227682',
    projectId: 'tm-book',
    storageBucket: 'tm-book.appspot.com',
    iosClientId: '174515227682-9lioso6m0psjavgnkf6q4802q943ae16.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookTiming',
  );
}
