// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYtQLcdX-pyW1MQOGqsFHJew0BTopN_Tk',
    appId: '1:555011840074:web:bbeb3e27088c861a3baeb3',
    messagingSenderId: '555011840074',
    projectId: 'd7-book-timer',
    authDomain: 'd7-book-timer.firebaseapp.com',
    storageBucket: 'd7-book-timer.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu-uU9IOCaewYMOZz8Voojh0YANIeCap0',
    appId: '1:555011840074:android:faa54e790b29c3d93baeb3',
    messagingSenderId: '555011840074',
    projectId: 'd7-book-timer',
    storageBucket: 'd7-book-timer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPn3_isxyzyyskrVemOGHucsnRgMBnQW8',
    appId: '1:555011840074:ios:12e707fc706efba73baeb3',
    messagingSenderId: '555011840074',
    projectId: 'd7-book-timer',
    storageBucket: 'd7-book-timer.appspot.com',
    iosClientId: '555011840074-bdt3resk9u9qcql7ph3v76li6rqtfidp.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookTimer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPn3_isxyzyyskrVemOGHucsnRgMBnQW8',
    appId: '1:555011840074:ios:12e707fc706efba73baeb3',
    messagingSenderId: '555011840074',
    projectId: 'd7-book-timer',
    storageBucket: 'd7-book-timer.appspot.com',
    iosClientId: '555011840074-bdt3resk9u9qcql7ph3v76li6rqtfidp.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookTimer',
  );
}
